name: CI/CD Frontend — Innovatech Chile (Fargate)

on:
  push:
    branches:
      - deploy

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 162455266988.dkr.ecr.us-east-1.amazonaws.com
  ECS_CLUSTER: innovatech-cluster

jobs:
  deploy:
    name: Build, Push & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push to ECR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/innovatech-frontend:latest
            ${{ env.ECR_REGISTRY }}/innovatech-frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Render task definition
        run: |
          TASK_DEF_ARN=$(aws ecs describe-services \
            --cluster ${{ env.ECS_CLUSTER }} \
            --services innovatech-frontend-task-service-ei964r2h \
            --query 'services[0].taskDefinition' \
            --output text)
          echo "Current task definition: $TASK_DEF_ARN"
          TASK_DEF=$(aws ecs describe-task-definition \
            --task-definition "$TASK_DEF_ARN" \
            --query 'taskDefinition' --output json)
          echo "$TASK_DEF" | jq 'del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy, .deregisteredAt) | .containerDefinitions[0].image = "${{ env.ECR_REGISTRY }}/innovatech-frontend:${{ github.sha }}"' > task-definition.json

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: task-definition.json
          service: innovatech-frontend-task-service-ei964r2h
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
